### ISSUE TITLE
img1

### ISSUE THREAD

**Issue by MurielMessias** [DarkSidarael/DarkSiderael#1]
![muriel (1)](https://github.com/DarkSidarael/DarkSiderael/assets/155545873/b0bd9edc-7381-4122-9e32-e1696ef2885f)

**Comment by DarkSidarael** [comment]
> ![muriel (1)](https://private-user-images.githubusercontent.com/155545873/322953940-b0bd9edc-7381-4122-9e32-e1696ef2885f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyOTE0MzgsIm5iZiI6MTcxMzI5MTEzOCwicGF0aCI6Ii8xNTU1NDU4NzMvMzIyOTUzOTQwLWIwYmQ5ZWRjLTczODEtNDEyMi05ZTMyLWUxNjk2ZWYyODg1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxODEyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWI3OTA1MjIzNDA2MjMwY2Y4ODU3MjNiZTdmMTMwYWNkYjU1ZTk4ZGVlYTc5ODY4MWU0MWUyYmJiYjU2ZjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Myto5GSWNQQQxwxOf1odvKdKs6_KIweT3WfzJ7xnEW0)
